IF OBJECT_ID('Users') IS NULL
CREATE TABLE Users
(
    [Id] UNIQUEIDENTIFIER NOT NULL DEFAULT (NEWID()),
    [Password] NVARCHAR(500) COLLATE ARABIC_CI_AI DEFAULT(''),
    [Email] NVARCHAR(250) COLLATE ARABIC_CI_AI DEFAULT('') UNIQUE,
    [Name] NVARCHAR(250) COLLATE ARABIC_CI_AI DEFAULT(''),
    [Role] NVARCHAR(250) COLLATE ARABIC_CI_AI DEFAULT(''),
    CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED
	(
		Id ASC
	)
)
GO
IF OBJECT_ID('UserSessions') IS NULL
CREATE TABLE UserSessions
(
    [Id] UNIQUEIDENTIFIER NOT NULL DEFAULT (NEWID()),
    [UserId] UNIQUEIDENTIFIER,
    [Stamp] DATETIME DEFAULT(GETDATE()),
    CONSTRAINT [PK_UserSessions] PRIMARY KEY CLUSTERED
	(
		Id ASC
	)
)
GO
IF OBJECT_ID('Books') IS NULL
CREATE TABLE Books
(
    [Id] UNIQUEIDENTIFIER NOT NULL DEFAULT (NEWID()),
    [Name] NVARCHAR(250) COLLATE ARABIC_CI_AI DEFAULT('') UNIQUE,
    [Author] NVARCHAR(250) COLLATE ARABIC_CI_AI DEFAULT(''),
    [Genre] NVARCHAR(250) COLLATE ARABIC_CI_AI DEFAULT(''),
    CONSTRAINT [PK_Books] PRIMARY KEY CLUSTERED
	(
		Id ASC
	)
)
GO
IF OBJECT_ID('Borrows') IS NULL
CREATE TABLE Borrows
(
    [Id] UNIQUEIDENTIFIER NOT NULL DEFAULT (NEWID()),
    [UserId] UNIQUEIDENTIFIER,
    [BookId] UNIQUEIDENTIFIER,
    [StartDate] DATETIME DEFAULT(GETDATE()),
    [EndDate] DATETIME DEFAULT(GETDATE()),
    [Active] BIT,
    CONSTRAINT [PK_Reservations] PRIMARY KEY CLUSTERED
	(
		[Id] ASC
	)
)
GO
INSERT [dbo].[Books] ([Id], [Name], [Author], [Genre]) VALUES (N'493a3cc8-5668-4250-b282-54f4177f589b', N'Lockjaw: Who''s A Good Boy', N' Ryan North', N'Science')
GO
INSERT [dbo].[Books] ([Id], [Name], [Author], [Genre]) VALUES (N'3f754892-1861-4e5a-8606-dbfc2970b987', N'Amazing Spider-Man: Learning To Crawl', N'Dan Slott', N'Science')
GO
INSERT [dbo].[Users] ([Id], [Password], [Email], [Name], [Role]) VALUES (N'69eed43c-1762-4f9a-ba1d-96702e711e05', N'KEkYC3GR0GfUm64XjuHmUg==', N'admin@admin.com', N'admin', N'User')
GO