IF OBJECT_ID('Users') IS NULL
CREATE TABLE Users
(
    [Id] UNIQUEIDENTIFIER NOT NULL DEFAULT (NEWID()),
    [Password] NVARCHAR(500) COLLATE ARABIC_CI_AI DEFAULT(''),
    [Email] NVARCHAR(250) COLLATE ARABIC_CI_AI DEFAULT('') UNIQUE,
    [Name] NVARCHAR(250) COLLATE ARABIC_CI_AI DEFAULT(''),
    [Role] NVARCHAR(250) COLLATE ARABIC_CI_AI DEFAULT(''),
    CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED
	(
		Id ASC
	)
)
GO
IF OBJECT_ID('UserSessions') IS NULL
CREATE TABLE UserSessions
(
    [Id] UNIQUEIDENTIFIER NOT NULL DEFAULT (NEWID()),
    [UserId] UNIQUEIDENTIFIER,
    [Stamp] DATETIME DEFAULT(GETDATE()),
    CONSTRAINT [PK_UserSessions] PRIMARY KEY CLUSTERED
	(
		Id ASC
	)
)
GO
IF OBJECT_ID('Books') IS NULL
CREATE TABLE Books
(
    [Id] UNIQUEIDENTIFIER NOT NULL DEFAULT (NEWID()),
    [Name] NVARCHAR(250) COLLATE ARABIC_CI_AI DEFAULT('') UNIQUE,
    [Author] NVARCHAR(250) COLLATE ARABIC_CI_AI DEFAULT(''),
    [Genre] NVARCHAR(250) COLLATE ARABIC_CI_AI DEFAULT(''),
    CONSTRAINT [PK_Books] PRIMARY KEY CLUSTERED
	(
		Id ASC
	)
)
GO
IF OBJECT_ID('Borrows') IS NULL
CREATE TABLE Borrows
(
    [Id] UNIQUEIDENTIFIER NOT NULL DEFAULT (NEWID()),
    [UserId] UNIQUEIDENTIFIER,
    [BookId] UNIQUEIDENTIFIER,
    [StartDate] DATETIME DEFAULT(GETDATE()),
    [EndDate] DATETIME DEFAULT(GETDATE()),
    [Active] BIT,
    CONSTRAINT [PK_Reservations] PRIMARY KEY CLUSTERED
	(
		[Id] ASC
	)
)
GO